services:
  pgdb1:
    build: ./db1
    env_file:
      - .env
      - ./db1/.env
    ports:
      - "${POSTGRES_DB1_PORT}:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
      - ./letsencrypt/certs:/etc/postgresql/ssl:ro

  pgdb2:
    build: ./db2
    env_file:
      - .env
      - ./db2/.env
    ports:
      - "${POSTGRES_DB2_PORT}:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
      - ./letsencrypt/certs:/etc/postgresql/ssl:ro

volumes:
  postgres_data1:
  postgres_data2:
